version: '2'
services:
  smishing:
    build: ./
    #volumes:
    #  - ./app:/app
    ports:
      - "8080:80"
    environment:
      - AWS_ACCESS_KEY_ID=<<-------------------->>
      - AWS_SECRET_ACCESS_KEY=R<<------------------------------------->>
      - AWS_REGION=ap-northeast-2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_DB=db
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
  redis:
    image: redis:alpine
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'smishing'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
